/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentifier un utilisateur */
        post: operations["a7997e7c1e3bfed64d4e56de82415931"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Révoquer le token courant */
        post: operations["f6b8957b4c0b25636613a9f0512a8ba9"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Utilisateur courant */
        get: operations["37d33f0281f67d31d05b4c45eea0143b"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/avocats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des avocats */
        get: operations["5414f45b91fece1941023a67c10c6aba"];
        put?: never;
        /** Créer un avocat (et son compte utilisateur) */
        post: operations["f3a11d876b9dcb549310f1614005dc36"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/avocats/{avocat}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un avocat */
        get: operations["1d6f9d9e138ae82e14b87eed9706a605"];
        /** Modifier un avocat */
        put: operations["c1bb164ce85bc4a49de03a8a5e3b1b57"];
        post?: never;
        /** Désactiver un avocat */
        delete: operations["62fc8c27a1d54de2cb997bcb2b2ea900"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des clients */
        get: operations["3dc702c49ee2caa5dd56328483587398"];
        put?: never;
        /** Créer un client */
        post: operations["fa5db0d5e257989e36bfe9cc2de663c2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistiques clients */
        get: operations["2dfa189e82335eb1b2dcf90af54948d9"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un client */
        get: operations["c1aaafb8e0a93e996c1d5fcb7ce893ac"];
        /** Modifier un client */
        put: operations["38c1cde835bc6dc56cf23070c5ae54c9"];
        post?: never;
        /** Supprimer un client */
        delete: operations["987cd6d1e54655f7e49e981591263c2c"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export CSV des clients */
        get: operations["fd262165664203513e5a69d868b72ae3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPI du tableau de bord */
        get: operations["00464eac0b2daa2b7dfd173ce52781f0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/activite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activité sur 7 jours (dossiers ouverts + rendez-vous) */
        get: operations["d9840087c3a804f899b1ecd7403182a3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/dossiers-recents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 5 derniers dossiers */
        get: operations["1fcadb27f1e4346899e40c32a72cf05f"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des documents */
        get: operations["a3f72d0f1040078409cdb8a1ee21d40b"];
        put?: never;
        /** Uploader un document (stockage privé) */
        post: operations["5c98d63549356cb0e0900901fd142d56"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistiques documents */
        get: operations["5e675dced9f52112eba9fff36dd58014"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un document */
        get: operations["c5241de6309b57267ad914888f95ca9a"];
        put?: never;
        post?: never;
        /** Supprimer un document */
        delete: operations["867bc0947afcbba0319db67b27716bea"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Télécharger un document (vérifie la policy) */
        get: operations["2269b642a56d2b65df5ba7eea5bf721b"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dossiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des dossiers */
        get: operations["3639c07930436dd8ce5efde3abb52d4b"];
        put?: never;
        /** Créer un dossier */
        post: operations["464dbe49079bf88a59ebcb47a69596ef"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dossiers/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistiques des dossiers */
        get: operations["dfc677316fa473b3e3c8825452253e89"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dossiers/{dossier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un dossier */
        get: operations["23ebf728f29d12d57f70a5ebe4df6018"];
        /** Modifier un dossier */
        put: operations["d0c471e016c5c88320fe22611b08029d"];
        post?: never;
        /** Supprimer un dossier */
        delete: operations["c769a8a231e5aaff9f1b492acabe042c"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dossiers/{dossier}/statut": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Changer le statut d'un dossier */
        patch: operations["6a05909149bfce0cd754c438661dff36"];
        trace?: never;
    };
    "/api/v1/dossiers/{dossier}/avocats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attacher ou détacher des avocats */
        post: operations["c9aac39619e001102abd127bdca3d07e"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evenements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des évènements */
        get: operations["67e6473ed23851b615eb46e892c828e5"];
        put?: never;
        /** Créer un évènement */
        post: operations["75bea6238c4386b83a5d9ce897bbebf5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evenements/{evenement}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un évènement */
        get: operations["a0c8249285e62bac2e3343cac8c65952"];
        /** Modifier un évènement */
        put: operations["73e214a5884dc0d4abd85112bdaa8a1a"];
        post?: never;
        /** Supprimer un évènement */
        delete: operations["b1c038a2ca32cd3a58d6338c6a2b99b8"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des factures */
        get: operations["9f77f3471a110c9fd8c1f9c6d82e9e25"];
        put?: never;
        /** Créer une facture avec ses lignes */
        post: operations["6fc95a208a56c44157c7a214ee6a2439"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factures/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistiques de facturation */
        get: operations["ee1e7e27648c44dd5022d597a2f0dd13"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factures/{facture}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'une facture */
        get: operations["c4ad48cad56c060b600a053ec88f441b"];
        /** Modifier une facture */
        put: operations["c092a3bdba1fe68a6112424f58fe3743"];
        post?: never;
        /** Supprimer une facture */
        delete: operations["3384c684f5ddac9968b2a8fa5218f6a9"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factures/{facture}/paiements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enregistrer un paiement */
        post: operations["781a9713e32354f5d05aa9d7b24e92d3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factures/{facture}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Télécharger le PDF d'une facture */
        get: operations["03dfd6a975911077a654e635a97cd525"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Avocat: {
            nom: string;
            prenom: string;
            specialite?: string | null;
            telephone?: string | null;
            barreau?: string | null;
            actif?: boolean;
            /** Format: email */
            email?: string;
            /** Format: password */
            password?: string;
        };
        Client: {
            /** @enum {string} */
            type_client: "particulier" | "societe";
            nom: string;
            prenom?: string | null;
            raison_sociale?: string | null;
            /** Format: email */
            email?: string | null;
            telephone?: string | null;
            adresse?: string | null;
            nif?: string | null;
            stat?: string | null;
            actif?: boolean;
        };
        Dossier: {
            client_id: number;
            titre: string;
            description?: string | null;
            type_droit: string;
            /** @enum {string} */
            statut?: "en_cours" | "en_revision" | "en_attente" | "cloture";
            /** @enum {string} */
            priorite?: "normale" | "haute" | "urgente";
            avancement?: number;
            /** @description Montant en Ariary (entier) */
            montant?: number | null;
            /** Format: date */
            date_ouverture: string;
            /** Format: date */
            date_cloture?: string | null;
            avocat_ids?: number[];
        };
        Evenement: {
            titre: string;
            /** @enum {string} */
            type: "rendez_vous" | "audience" | "echeance";
            /** Format: date-time */
            debut: string;
            /** Format: date-time */
            fin?: string | null;
            dossier_id?: number | null;
            client_id?: number | null;
            lieu?: string | null;
            description?: string | null;
        };
        Facture: {
            client_id: number;
            dossier_id?: number | null;
            /** Format: date */
            date_facture: string;
            /** Format: date */
            date_echeance: string;
            /** @enum {string} */
            statut?: "brouillon" | "en_attente" | "payee" | "annulee";
            notes?: string | null;
            lignes: {
                designation?: string;
                quantite?: number;
                /** @description En Ariary (entier) */
                prix_unitaire?: number;
            }[];
        };
        Paiement: {
            /** @description En Ariary (entier) */
            montant: number;
            /** @enum {string} */
            mode: "especes" | "virement" | "mobile_money" | "cheque";
            /** Format: date */
            date_paiement: string;
            reference?: string | null;
            notes?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    a7997e7c1e3bfed64d4e56de82415931: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Connexion réussie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token?: string;
                        role?: string;
                        user?: Record<string, never>;
                    };
                };
            };
            /** @description Identifiants invalides */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    f6b8957b4c0b25636613a9f0512a8ba9: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Déconnexion réussie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "37d33f0281f67d31d05b4c45eea0143b": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil utilisateur */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user?: Record<string, never>;
                        role?: string;
                    };
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "5414f45b91fece1941023a67c10c6aba": {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pagination des avocats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    f3a11d876b9dcb549310f1614005dc36: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Avocat"];
            };
        };
        responses: {
            /** @description Avocat créé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "1d6f9d9e138ae82e14b87eed9706a605": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                avocat: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Avocat */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    c1bb164ce85bc4a49de03a8a5e3b1b57: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                avocat: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Avocat"];
            };
        };
        responses: {
            /** @description Avocat modifié */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "62fc8c27a1d54de2cb997bcb2b2ea900": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                avocat: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Avocat désactivé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "3dc702c49ee2caa5dd56328483587398": {
        parameters: {
            query?: {
                type?: "particulier" | "societe";
                search?: string;
                sort?: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pagination des clients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    fa5db0d5e257989e36bfe9cc2de663c2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Client"];
            };
        };
        responses: {
            /** @description Client créé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "2dfa189e82335eb1b2dcf90af54948d9": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistiques */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    c1aaafb8e0a93e996c1d5fcb7ce893ac: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "38c1cde835bc6dc56cf23070c5ae54c9": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Client"];
            };
        };
        responses: {
            /** @description Client modifié */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "987cd6d1e54655f7e49e981591263c2c": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    fd262165664203513e5a69d868b72ae3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fichier CSV */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "00464eac0b2daa2b7dfd173ce52781f0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistiques */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    d9840087c3a804f899b1ecd7403182a3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Série temporelle pour Recharts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "1fcadb27f1e4346899e40c32a72cf05f": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dossiers récents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    a3f72d0f1040078409cdb8a1ee21d40b: {
        parameters: {
            query?: {
                search?: string;
                categorie_document_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pagination des documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "5c98d63549356cb0e0900901fd142d56": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                    dossier_id?: number;
                    categorie_document_id?: number;
                };
            };
        };
        responses: {
            /** @description Document uploadé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "5e675dced9f52112eba9fff36dd58014": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistiques */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    c5241de6309b57267ad914888f95ca9a: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "867bc0947afcbba0319db67b27716bea": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "2269b642a56d2b65df5ba7eea5bf721b": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fichier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "3639c07930436dd8ce5efde3abb52d4b": {
        parameters: {
            query?: {
                statut?: string;
                type_droit?: string;
                priorite?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pagination des dossiers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "464dbe49079bf88a59ebcb47a69596ef": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Dossier"];
            };
        };
        responses: {
            /** @description Dossier créé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dfc677316fa473b3e3c8825452253e89: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistiques */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "23ebf728f29d12d57f70a5ebe4df6018": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dossier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dossier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    d0c471e016c5c88320fe22611b08029d: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dossier: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Dossier"];
            };
        };
        responses: {
            /** @description Dossier modifié */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    c769a8a231e5aaff9f1b492acabe042c: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dossier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dossier supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "6a05909149bfce0cd754c438661dff36": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dossier: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    statut: "en_cours" | "en_revision" | "en_attente" | "cloture";
                    avancement?: number;
                };
            };
        };
        responses: {
            /** @description Dossier mis à jour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    c9aac39619e001102abd127bdca3d07e: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dossier: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    avocat_ids: number[];
                    roles?: string[];
                };
            };
        };
        responses: {
            /** @description Avocats synchronisés */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "67e6473ed23851b615eb46e892c828e5": {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pagination des évènements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "75bea6238c4386b83a5d9ce897bbebf5": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Evenement"];
            };
        };
        responses: {
            /** @description Évènement créé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    a0c8249285e62bac2e3343cac8c65952: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evenement: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Évènement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "73e214a5884dc0d4abd85112bdaa8a1a": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evenement: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Evenement"];
            };
        };
        responses: {
            /** @description Évènement modifié */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    b1c038a2ca32cd3a58d6338c6a2b99b8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evenement: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Évènement supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "9f77f3471a110c9fd8c1f9c6d82e9e25": {
        parameters: {
            query?: {
                statut?: string;
                client_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pagination des factures */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "6fc95a208a56c44157c7a214ee6a2439": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Facture"];
            };
        };
        responses: {
            /** @description Facture créée */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ee1e7e27648c44dd5022d597a2f0dd13: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistiques */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    c4ad48cad56c060b600a053ec88f441b: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facture: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Facture */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    c092a3bdba1fe68a6112424f58fe3743: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facture: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Facture"];
            };
        };
        responses: {
            /** @description Facture modifiée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "3384c684f5ddac9968b2a8fa5218f6a9": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facture: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Facture supprimée */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "781a9713e32354f5d05aa9d7b24e92d3": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facture: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Paiement"];
            };
        };
        responses: {
            /** @description Paiement enregistré */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Montant supérieur au solde */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "03dfd6a975911077a654e635a97cd525": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facture: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fichier PDF */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
